// <auto-generated />
using System;
using CompanyReviewsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyReviewsService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127054425_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyReviewsService.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanySize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("Headquarters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Global IT services",
                            CompanySize = "500,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1373),
                            FoundedYear = 1968,
                            Headquarters = "Mumbai, India",
                            Industry = "IT Services",
                            LogoUrl = "https://logo.clearbit.com/tcs.com",
                            Name = "TCS",
                            Website = "https://www.tcs.com"
                        },
                        new
                        {
                            Id = 2,
                            About = "Consulting & IT services",
                            CompanySize = "300,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1380),
                            FoundedYear = 1981,
                            Headquarters = "Bengaluru, India",
                            Industry = "IT Services",
                            LogoUrl = "https://logo.clearbit.com/infosys.com",
                            Name = "Infosys",
                            Website = "https://www.infosys.com"
                        },
                        new
                        {
                            Id = 3,
                            About = "IT & consulting",
                            CompanySize = "250,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1382),
                            FoundedYear = 1945,
                            Headquarters = "Bengaluru, India",
                            Industry = "IT Services",
                            LogoUrl = "https://logo.clearbit.com/wipro.com",
                            Name = "Wipro",
                            Website = "https://www.wipro.com"
                        },
                        new
                        {
                            Id = 4,
                            About = "Global IT enterprise",
                            CompanySize = "220,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1384),
                            FoundedYear = 1976,
                            Headquarters = "Noida, India",
                            Industry = "IT Services",
                            LogoUrl = "https://logo.clearbit.com/hcltech.com",
                            Name = "HCL Technologies",
                            Website = "https://www.hcltech.com"
                        },
                        new
                        {
                            Id = 5,
                            About = "Digital transformation",
                            CompanySize = "150,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1386),
                            FoundedYear = 1986,
                            Headquarters = "Pune, India",
                            Industry = "IT Services",
                            LogoUrl = "https://logo.clearbit.com/techmahindra.com",
                            Name = "Tech Mahindra",
                            Website = "https://www.techmahindra.com"
                        },
                        new
                        {
                            Id = 6,
                            About = "Professional services",
                            CompanySize = "700,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1387),
                            FoundedYear = 1989,
                            Headquarters = "Dublin, Ireland",
                            Industry = "Consulting",
                            LogoUrl = "https://logo.clearbit.com/accenture.com",
                            Name = "Accenture",
                            Website = "https://www.accenture.com"
                        },
                        new
                        {
                            Id = 7,
                            About = "IT consulting",
                            CompanySize = "350,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1389),
                            FoundedYear = 1967,
                            Headquarters = "Paris, France",
                            Industry = "Consulting",
                            LogoUrl = "https://logo.clearbit.com/capgemini.com",
                            Name = "Capgemini",
                            Website = "https://www.capgemini.com"
                        },
                        new
                        {
                            Id = 8,
                            About = "Digital transformation",
                            CompanySize = "300,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1391),
                            FoundedYear = 1994,
                            Headquarters = "New Jersey, USA",
                            Industry = "IT Services",
                            LogoUrl = "https://logo.clearbit.com/cognizant.com",
                            Name = "Cognizant",
                            Website = "https://www.cognizant.com"
                        },
                        new
                        {
                            Id = 9,
                            About = "Enterprise tech solutions",
                            CompanySize = "280,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1393),
                            FoundedYear = 1911,
                            Headquarters = "New York, USA",
                            Industry = "Technology",
                            LogoUrl = "https://logo.clearbit.com/ibm.com",
                            Name = "IBM",
                            Website = "https://www.ibm.com"
                        },
                        new
                        {
                            Id = 10,
                            About = "Cloud & AI products",
                            CompanySize = "220,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1396),
                            FoundedYear = 1975,
                            Headquarters = "Redmond, USA",
                            Industry = "Software",
                            LogoUrl = "https://logo.clearbit.com/microsoft.com",
                            Name = "Microsoft",
                            Website = "https://www.microsoft.com"
                        },
                        new
                        {
                            Id = 11,
                            About = "Search & AI",
                            CompanySize = "190,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1398),
                            FoundedYear = 1998,
                            Headquarters = "California, USA",
                            Industry = "Technology",
                            LogoUrl = "https://logo.clearbit.com/google.com",
                            Name = "Google",
                            Website = "https://www.google.com"
                        },
                        new
                        {
                            Id = 12,
                            About = "AWS & retail",
                            CompanySize = "1,500,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1400),
                            FoundedYear = 1994,
                            Headquarters = "Seattle, USA",
                            Industry = "Cloud & E-commerce",
                            LogoUrl = "https://logo.clearbit.com/amazon.com",
                            Name = "Amazon",
                            Website = "https://www.amazon.com"
                        },
                        new
                        {
                            Id = 13,
                            About = "Database solutions",
                            CompanySize = "160,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1402),
                            FoundedYear = 1977,
                            Headquarters = "Texas, USA",
                            Industry = "Enterprise Software",
                            LogoUrl = "https://logo.clearbit.com/oracle.com",
                            Name = "Oracle",
                            Website = "https://www.oracle.com"
                        },
                        new
                        {
                            Id = 14,
                            About = "ERP solutions",
                            CompanySize = "110,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1403),
                            FoundedYear = 1972,
                            Headquarters = "Germany",
                            Industry = "Enterprise Software",
                            LogoUrl = "https://logo.clearbit.com/sap.com",
                            Name = "SAP",
                            Website = "https://www.sap.com"
                        },
                        new
                        {
                            Id = 15,
                            About = "Business software",
                            CompanySize = "12,000+",
                            CreatedAt = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1405),
                            FoundedYear = 1996,
                            Headquarters = "Chennai, India",
                            Industry = "Software",
                            LogoUrl = "https://logo.clearbit.com/zoho.com",
                            Name = "Zoho",
                            Website = "https://www.zoho.com"
                        });
                });

            modelBuilder.Entity("CompanyReviewsService.Models.CompanyRatingSummary", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("AvgCareerGrowth")
                        .HasColumnType("float");

                    b.Property<double>("AvgCompensation")
                        .HasColumnType("float");

                    b.Property<double>("AvgCulture")
                        .HasColumnType("float");

                    b.Property<double>("AvgJobSecurity")
                        .HasColumnType("float");

                    b.Property<double>("AvgManagement")
                        .HasColumnType("float");

                    b.Property<double>("AvgOverallRating")
                        .HasColumnType("float");

                    b.Property<double>("AvgWorkLifeBalance")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompanyRatingSummaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1574),
                            TotalReviews = 100
                        },
                        new
                        {
                            Id = 2,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1591),
                            TotalReviews = 200
                        },
                        new
                        {
                            Id = 3,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1604),
                            TotalReviews = 300
                        },
                        new
                        {
                            Id = 4,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1618),
                            TotalReviews = 400
                        },
                        new
                        {
                            Id = 5,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1631),
                            TotalReviews = 500
                        },
                        new
                        {
                            Id = 6,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1646),
                            TotalReviews = 600
                        },
                        new
                        {
                            Id = 7,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1657),
                            TotalReviews = 700
                        },
                        new
                        {
                            Id = 8,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1669),
                            TotalReviews = 800
                        },
                        new
                        {
                            Id = 9,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1681),
                            TotalReviews = 900
                        },
                        new
                        {
                            Id = 10,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1694),
                            TotalReviews = 1000
                        },
                        new
                        {
                            Id = 11,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1707),
                            TotalReviews = 1100
                        },
                        new
                        {
                            Id = 12,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1721),
                            TotalReviews = 1200
                        },
                        new
                        {
                            Id = 13,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1734),
                            TotalReviews = 1300
                        },
                        new
                        {
                            Id = 14,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1807),
                            TotalReviews = 1400
                        },
                        new
                        {
                            Id = 15,
                            AvgCareerGrowth = 3.7999999999999998,
                            AvgCompensation = 3.7000000000000002,
                            AvgCulture = 3.8999999999999999,
                            AvgJobSecurity = 4.0,
                            AvgManagement = 3.5,
                            AvgOverallRating = 3.5,
                            AvgWorkLifeBalance = 3.6000000000000001,
                            LastUpdated = new DateTime(2026, 1, 27, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1821),
                            TotalReviews = 1500
                        });
                });

            modelBuilder.Entity("CompanyReviewsService.Models.CompanyReview", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AdviceToManagement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CareerGrowth")
                        .HasColumnType("int");

                    b.Property<int>("CompensationBenefits")
                        .HasColumnType("int");

                    b.Property<string>("Cons")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Culture")
                        .HasColumnType("int");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("JobSecurity")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Management")
                        .HasColumnType("int");

                    b.Property<double>("OverallRating")
                        .HasColumnType("float");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkLifeBalance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompanyReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdviceToManagement = "Improve hikes",
                            CareerGrowth = 3,
                            CompensationBenefits = 3,
                            Cons = "Slow growth",
                            CreatedAt = new DateTime(2025, 12, 28, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1848),
                            Culture = 4,
                            EmploymentStatus = "Current Employee",
                            IsAnonymous = true,
                            IsApproved = true,
                            JobSecurity = 5,
                            JobTitle = "Software Engineer",
                            Location = "Pune",
                            Management = 4,
                            OverallRating = 4.0,
                            Pros = "Job security",
                            WorkLifeBalance = 3
                        },
                        new
                        {
                            Id = 2,
                            AdviceToManagement = "Maintain balance",
                            CareerGrowth = 5,
                            CompensationBenefits = 5,
                            Cons = "High workload",
                            CreatedAt = new DateTime(2026, 1, 17, 5, 44, 24, 762, DateTimeKind.Utc).AddTicks(1860),
                            Culture = 5,
                            EmploymentStatus = "Current Employee",
                            IsAnonymous = false,
                            IsApproved = true,
                            JobSecurity = 5,
                            JobTitle = "Senior Developer",
                            Location = "Hyderabad",
                            Management = 4,
                            OverallRating = 4.7999999999999998,
                            Pros = "Pay & culture",
                            WorkLifeBalance = 2
                        });
                });

            modelBuilder.Entity("CompanyReviewsService.Models.CompanyRatingSummary", b =>
                {
                    b.HasOne("CompanyReviewsService.Models.Company", "Company")
                        .WithOne("RatingSummary")
                        .HasForeignKey("CompanyReviewsService.Models.CompanyRatingSummary", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompanyReviewsService.Models.CompanyReview", b =>
                {
                    b.HasOne("CompanyReviewsService.Models.Company", "Company")
                        .WithMany("Reviews")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompanyReviewsService.Models.Company", b =>
                {
                    b.Navigation("RatingSummary")
                        .IsRequired();

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
