// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestService.Data;

#nullable disable

namespace TestService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127154726_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestService.Model.CandidateTestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("McqTestId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("McqTestId");

                    b.ToTable("CandidateTestAttempts");
                });

            modelBuilder.Entity("TestService.Model.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Google"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Meta"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Netflix"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 8,
                            Name = "IBM"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Oracle"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Adobe"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Salesforce"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Uber"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Airbnb"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Spotify"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Twitter/X"
                        },
                        new
                        {
                            Id = 16,
                            Name = "LinkedIn"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Intel"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Cisco"
                        },
                        new
                        {
                            Id = 19,
                            Name = "PayPal"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Stripe"
                        });
                });

            modelBuilder.Entity("TestService.Model.McqOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("McqQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("McqQuestionId");

                    b.ToTable("McqOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = true,
                            McqQuestionId = 1,
                            OptionText = "Time complexity analysis"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            McqQuestionId = 1,
                            OptionText = "UI design"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            McqQuestionId = 1,
                            OptionText = "Database indexing"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            McqQuestionId = 1,
                            OptionText = "Networking protocol"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = true,
                            McqQuestionId = 2,
                            OptionText = "Java"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            McqQuestionId = 2,
                            OptionText = "Python"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = false,
                            McqQuestionId = 2,
                            OptionText = "Swift"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            McqQuestionId = 2,
                            OptionText = "Go"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = true,
                            McqQuestionId = 3,
                            OptionText = "Java Virtual Machine"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = false,
                            McqQuestionId = 3,
                            OptionText = "Java Variable Method"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = false,
                            McqQuestionId = 3,
                            OptionText = "Just Virtual Memory"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            McqQuestionId = 3,
                            OptionText = "None"
                        });
                });

            modelBuilder.Entity("TestService.Model.McqQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("McqTestId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("McqTestId");

                    b.ToTable("McqQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            McqTestId = 1,
                            QuestionText = "What is Big-O notation used for?"
                        },
                        new
                        {
                            Id = 2,
                            McqTestId = 1,
                            QuestionText = "Which language is Android primarily written in?"
                        },
                        new
                        {
                            Id = 3,
                            McqTestId = 1,
                            QuestionText = "What does JVM stand for?"
                        },
                        new
                        {
                            Id = 4,
                            McqTestId = 1,
                            QuestionText = "Which data structure uses FIFO?"
                        },
                        new
                        {
                            Id = 5,
                            McqTestId = 1,
                            QuestionText = "What is REST?"
                        },
                        new
                        {
                            Id = 6,
                            McqTestId = 2,
                            QuestionText = ".NET is developed by?"
                        },
                        new
                        {
                            Id = 7,
                            McqTestId = 2,
                            QuestionText = "What is CLR?"
                        },
                        new
                        {
                            Id = 8,
                            McqTestId = 2,
                            QuestionText = "Which language is used with ASP.NET Core?"
                        },
                        new
                        {
                            Id = 9,
                            McqTestId = 2,
                            QuestionText = "What does LINQ stand for?"
                        },
                        new
                        {
                            Id = 10,
                            McqTestId = 2,
                            QuestionText = "Which DB is from Microsoft?"
                        });
                });

            modelBuilder.Entity("TestService.Model.McqTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("McqTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            DurationMinutes = 30,
                            IsActive = true,
                            Title = "Google MCQ Test",
                            TotalQuestions = 5
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            DurationMinutes = 30,
                            IsActive = true,
                            Title = "Microsoft MCQ Test",
                            TotalQuestions = 5
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            DurationMinutes = 30,
                            IsActive = true,
                            Title = "Amazon MCQ Test",
                            TotalQuestions = 5
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 4,
                            DurationMinutes = 30,
                            IsActive = true,
                            Title = "Meta MCQ Test",
                            TotalQuestions = 5
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 5,
                            DurationMinutes = 30,
                            IsActive = true,
                            Title = "Netflix MCQ Test",
                            TotalQuestions = 5
                        });
                });

            modelBuilder.Entity("TestService.Model.CandidateTestAttempt", b =>
                {
                    b.HasOne("TestService.Model.McqTest", "McqTest")
                        .WithMany()
                        .HasForeignKey("McqTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McqTest");
                });

            modelBuilder.Entity("TestService.Model.McqOption", b =>
                {
                    b.HasOne("TestService.Model.McqQuestion", "McqQuestion")
                        .WithMany("Options")
                        .HasForeignKey("McqQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McqQuestion");
                });

            modelBuilder.Entity("TestService.Model.McqQuestion", b =>
                {
                    b.HasOne("TestService.Model.McqTest", "McqTest")
                        .WithMany("Questions")
                        .HasForeignKey("McqTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McqTest");
                });

            modelBuilder.Entity("TestService.Model.McqTest", b =>
                {
                    b.HasOne("TestService.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TestService.Model.McqQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("TestService.Model.McqTest", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
